table Naira
	lineageTag: 01129b20-2450-4d53-aa36-856bf33b28dc

	measure 'Forum of Top Posts by Views(Forum&Views)' = ```
			
			VAR CurrentTime = NOW()
			
			-- Step 1: Only posts from last 24 hours
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    )
			
			-- Step 2: Deduplicate each topic and capture its max views
			VAR UniqueTopics =
			    SUMMARIZE (
			        Last24Hrs,
			        Naira[NamTit],
			        Naira[Forum],
			        "Views", MAX ( Naira[Views] )
			    )
			
			-- Step 3: Sum all views for each forum
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "SumViews",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            SUMX (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum ),
			                [Views]
			            )
			    )
			
			-- Step 4: Forum with highest total views
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [SumViews], DESC )
			
			-- Step 5: Extract values
			VAR ForumName = MAXX ( TopForum, Naira[Forum] )
			VAR TotalViews = MAXX ( TopForum, [SumViews] )
			
			RETURN
			ForumName & UNICHAR(10) & FORMAT ( TotalViews, "#,0" ) & " Views"
			
			```
		lineageTag: c8cb4ed4-4349-41eb-b147-7a5cdcdc05fd

	measure 'Forums Count (Last 24Hrs)' = ```
			
			VAR CurrentTime = NOW()
			
			-- Step 1: Filter to only rows from the last 24 hours
			VAR Last24Hrs =
			    FILTER(
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1
			            && Naira[scrap_time] <= CurrentTime
			    )
			
			-- Step 2: Deduplicate by topic within that 24-hour window
			VAR UniqueTopics =
			    SUMMARIZE(
			        Last24Hrs,
			        Naira[NamTit],
			        Naira[Forum]
			    )
			
			-- Step 3: Count distinct forums among those unique topics
			RETURN
			COUNTROWS(
			    
			        SELECTCOLUMNS(UniqueTopics, "Forum", Naira[Forum])
			    )
			
			
			```
		formatString: 0
		lineageTag: 319e4315-8fee-489d-a1ad-6a065f71d536

	measure 'Front Page Post Count (Last 24Hrs)' = ```
			
			VAR UniqueTopics =
			    SUMMARIZE(
			        Naira,
			        Naira[NamTit],
			        Naira[Forum]
			    )
			
			RETURN
			COUNTROWS ( UniqueTopics)
			
			```
		formatString: 0
		lineageTag: 635fe43f-1fce-4325-b53d-cafeb628f1ef

	measure 'Highest Viewed Post (Last 24Hrs)' = ```
			
			VAR CurrentTime = NOW()
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    )
			VAR TopPost =
			    TOPN (
			        1,
			        Last24Hrs,
			        Naira[Views],
			        DESC
			    )
			RETURN
			MAXX ( TopPost, Naira[Posts] )
			
			```
		lineageTag: 14ec6e73-5461-44de-8c56-8f053756859a

	measure 'Least Forum (Last 24Hrs)' = ```
			
			
			
			-- Step 2: Deduplicate topics per forum in that 24-hour window
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        Naira[Forum]
			    )
			
			-- Step 3: Count how many unique topics each forum has
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "TopicCount",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            COUNTROWS (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum )
			            )
			    )
			
			-- Step 4: Identify the forum with the Lowest topic count
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [TopicCount], ASC )
			
			-- Step 5: Extract and format the result
			VAR ForumName = MINX ( TopForum, Naira[Forum] )
			VAR TopicCount = MINX ( TopForum, [TopicCount] )
			
			RETURN
			ForumName & ":  " & FORMAT ( TopicCount, "#,0" )
			
			```
		lineageTag: 1683b353-0922-4307-b2e7-a4fc6aff0925

	measure 'Max Guests Post Name (Last 24Hrs)' = ```
			
			VAR CurrentTime = NOW()
			-- Step 1: Filter data for the last 24 hours
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    ) 
			-- Step 1: Filter data for the last 24 hours
			
			-- Step 2: Get each topic and its guest count
			VAR UniqueTopics =
			    SUMMARIZE (
			        Last24Hrs,
			        Naira[NamTit],
			        "GuestCount", MAX ( Naira[guests] )
			    )
			-- Step 3: Find the topic with the highest number of guests
			VAR TopTopic =
			    TOPN ( 1, UniqueTopics, [GuestCount], DESC ) 
			-- Step 4: Extract values for display
			VAR TopicName = MAXX ( TopTopic, Naira[NamTit] )
			VAR GuestCount = MAXX ( TopTopic, [GuestCount] )
			
			RETURN
			TopicName
			
			```
		lineageTag: 33630cc9-7b52-4c29-b887-a1b02eb5fe85

	measure 'Top Forum (Last 24Hrs)' = ```
			
			-- Step 2: Deduplicate topics per forum in that 24-hour window
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        Naira[Forum]
			    )
			
			-- Step 3: Count how many unique topics each forum has
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "TopicCount",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            COUNTROWS (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum )
			            )
			    )
			
			-- Step 4: Identify the forum with the highest topic count
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [TopicCount], DESC )
			
			-- Step 5: Extract and format the result
			VAR ForumName = MAXX ( TopForum, Naira[Forum] )
			VAR TopicCount = MAXX ( TopForum, [TopicCount] )
			
			RETURN
			ForumName 
			
			```
		lineageTag: 29a71af6-1723-49ba-8373-394ef23441c1

	measure 'Top Forum guests' = ```
			
			VAR CurrentTime = NOW()
			 -- Step 1: Only posts from last 24 hours
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    ) 
			VAR UniqueTopics =
			    SUMMARIZE (
			        Last24Hrs,
			        Naira[NamTit],
			        Naira[Forum],
			        "Guests", MAX ( Naira[guests] )
			    ) 
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "SumGuests",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            SUMX (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum ),
			                [Guests]
			            )
			    )
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [SumGuests], DESC )
			
			-- Step 5: Extract values
			VAR ForumName = MAXX ( TopForum, Naira[Forum] )
			VAR TotalGuests = MAXX ( TopForum, [SumGuests] )
			
			RETURN
			 TotalGuests
			```
		formatString: 0
		lineageTag: e18b6998-b6f5-47d5-b62b-9254c4d9d5e7

	measure 'Top Forum Post Count (Last 24Hrs)' = ```
			
			VAR CurrentTime = NOW()
			VAR ForumCounts =
			    ADDCOLUMNS (
			        ALL ( Naira[Forum] ),   -- ignore forum slicers
			        "PostCount",
			        CALCULATE (
			            COUNTROWS ( Naira ),               -- count rows for this forum only
			            REMOVEFILTERS ( Naira[scrap_time] ),
			            Naira[scrap_time] > CurrentTime - 1,
			            Naira[scrap_time] <= CurrentTime
			        )
			    )
			RETURN
			MAXX ( ForumCounts, [PostCount] )
			
			```
		formatString: 0
		lineageTag: c7f6020d-3ee9-40ba-968b-2f0d4d7a2e86

	measure 'Top Forum Views' = ```
			
			
			
			-- Step 2: Deduplicate each topic and capture its max views
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        Naira[Forum],
			        "Views", MAX ( Naira[Views] )
			    )
			
			-- Step 3: Sum all views for each forum
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "SumViews",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            SUMX (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum ),
			                [Views]
			            )
			    )
			
			-- Step 4: Forum with highest total views
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [SumViews], DESC )
			
			-- Step 5: Extract values
			VAR ForumName = MAXX ( TopForum, Naira[Forum] )
			VAR TotalViews = MAXX ( TopForum, [SumViews] )
			
			RETURN
			 
			     TotalViews
			
			```
		formatString: 0
		lineageTag: d48f3ecd-9bc3-458e-a2fe-3b6eb8f31e9f

	measure 'Top Guests Post (Last 24Hrs)' = ```
			
			
			-- Step 2: Get each topic and its guest count
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        "GuestCount", MAX ( Naira[guests] )
			    )
			-- Step 3: Find the topic with the highest number of guests
			VAR TopTopic =
			    TOPN ( 1, UniqueTopics, [GuestCount], DESC ) 
			-- Step 4: Extract values for display
			VAR TopicName = MAXX ( TopTopic, Naira[NamTit] )
			VAR GuestCount = MAXX ( TopTopic, [GuestCount] )
			
			RETURN
			GuestCount
			
			```
		formatString: 0
		lineageTag: 333d3d71-6c21-43ef-95fc-cf1160da793c

	measure 'Top Poster (Last 24Hrs)' = ```
			
			
			VAR TopRow =
			    TOPN (
			        1,
			        Naira,
			        Naira[Views],
			        DESC
			    )
			RETURN
			MAXX ( TopRow, Naira[poster] )
			
			```
		lineageTag: adb74205-46a9-409d-a16c-007539cc7611

	measure 'Top Poster Views (Last 24Hrs)' = ```
			
			
			VAR TopRow =
			    TOPN (
			        1,
			        Naira,
			        Naira[Views],
			        DESC
			    )
			RETURN
			MAXX ( TopRow, Naira[Views] )
			
			```
		formatString: #,0
		lineageTag: 85f8a0d0-2505-4054-af7c-95b767e277a7

	measure 'Top Post(Views)' = ```
			
			
			VAR TopRow =
			    TOPN ( 1, Naira, Naira[Views], DESC )
			RETURN
			    SELECTCOLUMNS ( TopRow, "Top Post", Naira[Posts] )
			
			```
		lineageTag: e82c6837-a4d0-4fdc-a550-c9518cb6c431

	measure 'Last accessed' = ```
			
			
			VAR LastAccess =
			    MAX (  Naira[scrap_time] )
			
			RETURN
			    FORMAT ( LastAccess, "ddd, mmm dd, yyyy — hh:mm AM/PM" )
			
			
			```
		lineageTag: 50b43aeb-0a54-4d59-b773-5e42d24562a2

	measure 'Least Post(Views)' = ```
			
			
			VAR TopRow =
			    TOPN ( 1, Naira, Naira[Views], ASC )
			RETURN
			    SELECTCOLUMNS ( TopRow, "Top Post", Naira[Posts] )
			
			```
		lineageTag: 21ab20ce-ca7b-4d49-ad50-bcad93725869

	measure 'Least Poster (Views)' = ```
			
			VAR TopRow =
			    TOPN (
			        1,Naira,
			        Naira[Views],
			        ASC
			    )
			RETURN
			MINX ( TopRow, Naira[poster] )
			
			```
		lineageTag: 393c24a7-34a0-423c-a489-a24165ca1834

	measure 'Least Guests Post (Last 24Hrs)' = ```
			
			-- Step 2: Get each topic and its guest count
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        "GuestCount", MAX ( Naira[guests] )
			    )
			-- Step 3: Find the topic with the lowest number of guests
			VAR TopTopic =
			    TOPN ( 1, UniqueTopics, [GuestCount], ASC ) 
			-- Step 4: Extract values for display
			VAR TopicName = MINX ( TopTopic, Naira[NamTit] )
			VAR GuestCount = MINX ( TopTopic, [GuestCount] )
			
			RETURN
			GuestCount
			
			```
		formatString: 0
		lineageTag: 856b00f2-e742-4fea-904e-00d56e0fb0c1

	measure 'Least Poster Guests (Last 24Hrs)' = ```
			
			
			-- Step 2: Get each topic and its guest count
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        Naira[poster],
			        "GuestCount", MAX ( Naira[guests] )
			    )
			-- Step 3: Find the topic with the lowest number of guests
			VAR TopTopic =
			    TOPN ( 1, UniqueTopics, [GuestCount], ASC ) 
			-- Step 4: Extract values for display
			VAR TopicName = MINX ( TopTopic, Naira[NamTit] )
			VAR GuestCount = MINX ( TopTopic, [GuestCount] )
			VAR Poxter = MINX(TopTopic, Naira[Poster])
			
			RETURN
			Poxter
			
			
			```
		lineageTag: e470469d-52dd-437f-9ff5-b1ce4faa67c7

	measure 'Least Poster Views (Last 24Hrs)' = ```
			
			
			VAR TopRow =
			    TOPN (
			        1,
			        Naira,
			        Naira[Views],
			        ASC
			    )
			RETURN
			MINX ( TopRow, Naira[Views] )
			
			```
		formatString: 0
		lineageTag: 24e14848-7711-4125-91fd-f3c1a5706810

	measure 'Least Forum Views' = ```
			
			VAR CurrentTime = NOW()
			
			-- Step 1: Only posts from last 24 hours
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    )
			
			-- Step 2: Deduplicate each topic and capture its max views
			VAR UniqueTopics =
			    SUMMARIZE (
			        Last24Hrs,
			        Naira[NamTit],
			        Naira[Forum],
			        "Views", MIN ( Naira[Views] )
			    )
			
			-- Step 3: Sum all views for each forum
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "SumViews",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            SUMX (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum ),
			                [Views]
			            )
			    )
			
			-- Step 4: Forum with highest total views
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [SumViews], ASC )
			
			-- Step 5: Extract values
			VAR ForumName = MINX ( TopForum, Naira[Forum] )
			VAR TotalViews = MINX ( TopForum, [SumViews] )
			
			RETURN
			 TotalViews
			
			```
		formatString: 0
		lineageTag: 31891f6a-728b-4331-b1c9-017acd8e2360

	measure 'Leasts Forum Count (Last 24Hrs)' = ```
			
			VAR CurrentTime = NOW()
			
			-- Step 1: Filter to only rows from the last 24 hours
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    )
			
			-- Step 2: Deduplicate topics per forum in that 24-hour window
			VAR UniqueTopics =
			    SUMMARIZE (
			        Last24Hrs,
			        Naira[NamTit],
			        Naira[Forum]
			    )
			
			-- Step 3: Count how many unique topics each forum has
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "TopicCount",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            COUNTROWS (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum )
			            )
			    )
			
			-- Step 4: Identify the forum with the highest topic count
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [TopicCount], ASC )
			
			-- Step 5: Extract and format the result
			VAR ForumName = MINX ( TopForum, Naira[Forum] )
			VAR TopicCount = MINX ( TopForum, [TopicCount] )
			
			RETURN
			ForumName & ":  " & FORMAT ( TopicCount, "#,0" )
			
			```
		lineageTag: 761ae070-9690-4f02-a14f-8d6dad0152f4

	measure 'Least Forum Name Views' = ```
			
			
			
			-- Step 2: Deduplicate each topic and capture its max views
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        Naira[Forum],
			        "Views", MAX ( Naira[Views] )
			    )
			
			-- Step 3: Sum all views for each forum
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "SumViews",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            SUMX (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum ),
			                [Views]
			            )
			    )
			
			-- Step 4: Forum with Lowest total views
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [SumViews], ASC )
			
			-- Step 5: Extract values
			VAR ForumName = MINX ( TopForum, Naira[Forum] )
			VAR TotalViews = MINX ( TopForum, [SumViews] )
			
			RETURN
			 ForumName & ":  " & FORMAT ( TotalViews, "#,0" )
			
			```
		lineageTag: f2b5d3ec-1c77-490d-953d-601b1db466b7

	measure 'Total Views (Last 24Hrs)' = ```
			
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        "Views", MAX ( Naira[Views] )
			    )
			VAR TotalViews =
			    SUMX ( UniqueTopics, [Views] )
			RETURN
			    TotalViews
			
			```
		formatString: 0
		lineageTag: 6ec551b2-1531-4d1b-a412-25cedd9003c9

	measure 'Front Page Views Last Access Time' = ```
			
			VAR CurrentTime = NOW()
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    )
			VAR LastAccess =
			    MAXX ( Last24Hrs, Naira[scrap_time] )
			RETURN
			    FORMAT ( LastAccess, "dd/mm/yyyy" )
			
			```
		lineageTag: f196249f-883b-48c0-887a-09ebf6a09663

	measure 'Total Guests (Last 24Hrs)' = ```
			
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        "Guests", MAX ( Naira[guests] )
			    )
			VAR TotalGuests =
			    SUMX ( UniqueTopics, [Guests] )
			RETURN
			    TotalGuests
			
			
			```
		formatString: 0
		lineageTag: cf04eedc-2af5-48de-99ff-25fdfe298014

	measure 'Top Poster Guests (Last 24Hrs)' = ```
			
			
			VAR TopRow =
			    TOPN (
			        1,
			        Naira,
			        Naira[guests],
			        DESC
			    )
			RETURN
			MAXX ( TopRow, Naira[poster] )
			
			
			```
		lineageTag: 98a304f0-9347-49e9-bbea-b471e1ecc76b

	measure 'Front Page Summary' = ```
			
			"Nairaland Front Page Post Analytics as at: " &
			
			Naira[Last accessed]
			
			```
		lineageTag: cf559e0c-ea75-42f4-8ae4-3ec4091e92e3

	measure 'Top Forum bar Views' = ```
			
			VAR CurrentTime = NOW()
			
			-- Step 1: Only posts from last 24 hours
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    )
			
			-- Step 2: Deduplicate each topic and capture its max views
			VAR UniqueTopics =
			    SUMMARIZE (
			        Last24Hrs,
			        Naira[NamTit],
			        Naira[Forum],
			        "Views", MAX ( Naira[Views] )
			    )
			
			-- Step 3: Sum all views for each forum
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "SumViews",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            SUMX (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum ),
			                [Views]
			            )
			    )
			
			-- Step 4: Forum with highest total views
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [SumViews], DESC )
			
			-- Step 5: Extract values
			VAR ForumName = MAXX ( TopForum, Naira[Forum] )
			VAR TotalViews = MAXX ( TopForum, [SumViews] )
			
			RETURN
			 
			    TotalViews
			
			```
		formatString: 0
		lineageTag: cfb136bb-0a9b-42c3-9599-e56ec957062a

	measure check = ```
			
			VAR CurrentTime = NOW()
			-- Step 1: Filter data for the last 24 hours
			VAR Last24Hrs =
			    FILTER (
			        Naira,
			        Naira[scrap_time] >= CurrentTime - 1 &&
			        Naira[scrap_time] <= CurrentTime
			    ) 
			-- Step 1: Filter data for the last 24 hours
			
			-- Step 2: Get each topic and its guest count
			VAR UniqueTopics =
			    SUMMARIZE (
			        Last24Hrs,
			        Naira[NamTit],
			        Naira[poster],
			        "GuestCount", MAX ( Naira[guests] )
			    )
			-- Step 3: Find the topic with the lowest number of guests
			VAR TopTopic =
			    TOPN ( 1, UniqueTopics, [GuestCount], ASC ) 
			-- Step 4: Extract values for display
			VAR TopicName = MINX ( TopTopic, Naira[NamTit] )
			VAR GuestCount = MINX ( TopTopic, [GuestCount] )
			VAR Poxter = MINX(TopTopic, Naira[Poster])
			
			RETURN
			Poxter
			
			```
		lineageTag: 0ee8e6ae-40ef-4b46-a8dc-11f327561e72

	measure 'Top Forum Count' = ```
			
			
			-- Step 2: Deduplicate topics per forum in that 24-hour window
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        Naira[Forum]
			    )
			
			-- Step 3: Count how many unique topics each forum has
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "TopicCount",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            COUNTROWS (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum )
			            )
			    )
			
			-- Step 4: Identify the forum with the highest topic count
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [TopicCount], DESC )
			
			-- Step 5: Extract and format the result
			VAR ForumName = MAXX ( TopForum, Naira[Forum] )
			VAR TopicCount = MAXX ( TopForum, [TopicCount] )
			
			RETURN
			ForumName 
			
			```
		lineageTag: 45496325-b013-4907-b4cf-e65308ca3109

	measure 'Top Forum Counts' = ```
			
			
			-- Step 2: Deduplicate topics per forum in that 24-hour window
			VAR UniqueTopics =
			    SUMMARIZE (
			        Naira,
			        Naira[NamTit],
			        Naira[Forum]
			    )
			
			-- Step 3: Count how many unique topics each forum has
			VAR ForumTopicCounts =
			    ADDCOLUMNS (
			        SUMMARIZE ( UniqueTopics, Naira[Forum] ),
			        "TopicCount",
			        VAR CurrentForum = Naira[Forum]
			        RETURN
			            COUNTROWS (
			                FILTER ( UniqueTopics, Naira[Forum] = CurrentForum )
			            )
			    )
			
			-- Step 4: Identify the forum with the highest topic count
			VAR TopForum =
			    TOPN ( 1, ForumTopicCounts, [TopicCount], DESC )
			
			-- Step 5: Extract and format the result
			VAR ForumName = MAXX ( TopForum, Naira[Forum] )
			VAR TopicCount = MAXX ( TopForum, [TopicCount] )
			
			RETURN
			TopicCount 
			
			```
		formatString: 0
		lineageTag: 9073e682-fcdf-498e-9c40-781a4899ca21

	column NamTit
		dataType: string
		lineageTag: 497c0b2d-d939-484f-8857-be0371c6fd57
		summarizeBy: none
		sourceColumn: NamTit

		annotation SummarizationSetBy = Automatic

	column Views
		dataType: int64
		formatString: 0
		lineageTag: c66c0699-e45c-405e-9094-e5bd95f940b5
		summarizeBy: sum
		sourceColumn: Views

		annotation SummarizationSetBy = Automatic

	column guests
		dataType: int64
		formatString: 0
		lineageTag: 99a01eef-cb40-488f-859d-9a23f04bbc94
		summarizeBy: sum
		sourceColumn: guests

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: string
		lineageTag: b8dbc48d-de6e-4e8a-9d9c-cc3b34bebc5f
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column poster
		dataType: string
		lineageTag: 034765d7-cdd2-4dc3-971f-9199cbd9c506
		summarizeBy: none
		sourceColumn: poster

		annotation SummarizationSetBy = Automatic

	column scrap_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 7563ecc3-0716-4da1-9175-f1d942d10ab7
		summarizeBy: none
		sourceColumn: scrap_time

		variation Variation
			isDefault
			relationship: 9618d8e5-30f6-4f15-a06a-f865f5a6057e
			defaultHierarchy: LocalDateTable_94924ef4-ee53-4c74-a76b-011405c5f3ff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Forum
		dataType: string
		lineageTag: 3ff9f05b-d46d-4c78-99a5-26e96505a50f
		summarizeBy: none
		sourceColumn: Forum

		annotation SummarizationSetBy = Automatic

	column Posts
		dataType: string
		lineageTag: 428e7877-8f78-4df2-bb42-df3b9a09c245
		summarizeBy: none
		sourceColumn: Posts

		annotation SummarizationSetBy = Automatic

	partition Naira = m
		mode: import
		source =
				let
				    // Connect to the ADLS Gen2 container
				    Source = AzureStorage.DataLake("https://lstor.dfs.core.windows.net/naircont"),
				
				    // Keep only JSON files
				    JSONFiles = Table.SelectRows(Source, each Text.EndsWith(Text.Lower([Name]), ".json")),
				
				    // Decode folder path (replace %3D with =, %2F with /)
				    AddDecodedPath = Table.AddColumn(
				        JSONFiles,
				        "DecodedPath",
				        each Text.Replace(Text.Replace([Folder Path], "%3D", "="), "%2F", "/")
				    ),
				
				    // Extract year, month, day, and hour from folder structure
				    AddParsedDateTime = Table.AddColumn(
				        AddDecodedPath,
				        "DateTimeKey",
				        each
				            let
				                Path = Text.Lower([DecodedPath]),
				                Year = try Number.FromText(Text.BetweenDelimiters(Path, "year=", "/")) otherwise null,
				                Month = try Number.FromText(Text.BetweenDelimiters(Path, "month=", "/")) otherwise null,
				                Day = try Number.FromText(Text.BetweenDelimiters(Path, "day=", "/")) otherwise null,
				                Hour = try Number.FromText(Text.BetweenDelimiters(Path, "hour=", "/")) otherwise 0,
				                DT = try #datetime(Year, Month, Day, Hour, 0, 0) otherwise null
				            in
				                DT
				    ),
				
				    // Keep only valid datetime rows
				    ValidFiles = Table.SelectRows(AddParsedDateTime, each [DateTimeKey] <> null),
				
				    // Identify the latest DateTimeKey
				    LatestDateTime =
				        if Table.IsEmpty(ValidFiles) then null else List.Max(ValidFiles[DateTimeKey]),
				
				    // Get the most recent JSON file row
				    LatestFile =
				        if LatestDateTime <> null then
				            Table.SelectRows(ValidFiles, each [DateTimeKey] = LatestDateTime)
				        else
				            #table({}, {}),
				
				    // Extract the binary content from that file
				    LatestFileBinary =
				        if Table.IsEmpty(LatestFile) then null else LatestFile{0}[Content],
				
				    // Parse JSON safely
				    ParsedJSON =
				        if LatestFileBinary = null then
				            null
				        else
				            try Json.Document(LatestFileBinary) otherwise null,
				
				    // Convert JSON to table regardless of structure
				    AsTable =
				        if ParsedJSON = null then
				            #table({}, {})
				        else if Value.Is(ParsedJSON, type list) then
				            Table.FromList(ParsedJSON, Splitter.SplitByNothing(), {"Column1"})
				        else if Value.Is(ParsedJSON, type record) then
				            Table.FromRecords({ParsedJSON})
				        else
				            #table({}, {}),
				
				    // Detect nested records and expand automatically
				    ColumnsToExpand =
				        if Table.IsEmpty(AsTable) then
				            {}
				        else if Table.HasColumns(AsTable, "Column1") then
				            List.Distinct(
				                List.Combine(
				                    List.Transform(
				                        Table.ToRecords(AsTable),
				                        each if Record.HasFields(_, "Column1") then Record.FieldNames(Record.Field(_, "Column1")) else {}
				                    )
				                )
				            )
				        else
				            Table.ColumnNames(AsTable),
				
				    Expanded =
				        if Table.IsEmpty(AsTable) then
				            AsTable
				        else if Table.HasColumns(AsTable, "Column1") and not List.IsEmpty(ColumnsToExpand) then
				            Table.ExpandRecordColumn(AsTable, "Column1", ColumnsToExpand, ColumnsToExpand)
				        else
				            AsTable,
				
				    // Apply data types safely
				    #"Changed Type" = try Table.TransformColumnTypes(Expanded, {
				        {"NamTit", type text},
				        {"Views", Int64.Type},
				        {"guests", Int64.Type},
				        {"timestamp", type any},
				        {"poster", type text},
				        {"scrap_time", type datetime}
				    }) otherwise Expanded,
				
				    // Filter out rows where Views = 0 (if column exists)
				    #"Filtered Rows" =
				        if Table.HasColumns(#"Changed Type", "Views") then
				            Table.SelectRows(#"Changed Type", each ([Views] <> 0))
				        else
				            #"Changed Type",
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows", "NamTit", "NamTit - Copy"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Column", "NamTit - Copy", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, true), {"NamTit - Copy.1", "NamTit - Copy.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"NamTit - Copy.1", type text}, {"NamTit - Copy.2", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"NamTit - Copy.2"}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Removed Columns", "NamTit - Copy.1", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, true), {"NamTit - Copy.1.1", "NamTit - Copy.1.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"NamTit - Copy.1.1", type text}, {"NamTit - Copy.1.2", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"NamTit - Copy.1.1", "Posts"}, {"NamTit - Copy.1.2", "Forum"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

