test = 
VAR CurrentTime = NOW()
VAR Last24Hrs =
    FILTER (
        Nairaland,
        Nairaland[newscraptime] >= CurrentTime - 1 &&
        Nairaland[newscraptime] <= CurrentTime
    )
VAR UniqueTopics =
    SUMMARIZE (
        Last24Hrs,
        Nairaland[NamTit],
        Nairaland[Forum]
    )
RETURN UniqueTopics
